### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by yoziru** [felixstorm/esphome-custom-components#1]
Could you please add a LICENSE to the repo? Interested in contributing to the zehnder esphome integration

**Comment by felixstorm** [comment]
Sorry for my very late reply. You're very welcome to contribute, but since this is just my personal repository that I use to pull my own custom components from I suggest that you just fork (or copy) the code and then publish the updated version yourself. My time unfortunately is very limited, so it will probably be very unlikely for me to check or accept pull requests besides very minor updates.

**Comment by yoziru** [comment]
Thanks for this! I forked and pushed my changes in https://github.com/yoziru/esphome-zehnder-comfoair
